---
# LAMP stack setup and configuration tasks.

- name: diable SELinux
  selinux:
    policy: targeted
    state: disabled
  register: st

- name: restart machine
  shell: sleep 2 && reboot
  async: 1
  ignore_errors: true
  when: st.changed

- name: waiting for server to come back
  local_action: wait_for host="{{ inventory_hostname }}" port=22 search_regex=OpenSSH delay=5 timeout=300
  connection: local
  become: false
  when: st.changed

